Ember.TEMPLATES["application"] = Ember.Handlebars.compile("<div class=\"navbar navbar-inverse navbar-fixed-top\">\r\n  <div class=\"navbar-inner\">\r\n    <div class=\"container-fluid\">\r\n      <button type=\"button\" class=\"btn btn-navbar\" data-toggle=\"collapse\" data-target=\".nav-collapse\">\r\n        <span class=\"icon-bar\"></span>\r\n        <span class=\"icon-bar\"></span>\r\n        <span class=\"icon-bar\"></span>\r\n      </button>\r\n      <a class=\"brand\" href=\"#\">Markdown Editor</a>\r\n      <div class=\"nav-collapse collapse\">\r\n        <p class=\"navbar-text pull-right\">\r\n          Logged in as <a href=\"#\" class=\"navbar-link\">{{name}}</a>\r\n        </p>\r\n        <ul class=\"nav\">\r\n          <li>{{#link-to 'index'}}Home{{/link-to}}</li>\r\n          <li>{{#link-to 'files'}}Files{{/link-to}}</li>\r\n          <li>{{#link-to 'files.new'}}Add File{{/link-to}}</li>\r\n        </ul>\r\n      </div>\r\n    </div>\r\n  </div>\r\n</div>\r\n{{outlet}}");

Ember.TEMPLATES["files"] = Ember.Handlebars.compile("<div class=\"container-fluid\">\r\n  <div class=\"row-fluid\">\r\n    <div class=\"span3\">        \r\n      <table class=\"table\">\r\n        {{#each file in model}}\r\n          <tr><td>\r\n            {{#link-to 'files.detail' file}}\r\n              {{file.title}} by {{file.author}}\r\n            {{/link-to}}\r\n            {{#link-to 'files.edit' file}}\r\n              <span class=\"btn\">Edit</span>\r\n            {{/link-to}}              \r\n          </td></tr>\r\n        {{/each}}\r\n      </table>\r\n    </div>      \r\n    <div class=\"span9 well\">\r\n      {{outlet}}\r\n    </div>\r\n  </div>\r\n</div>");

Ember.TEMPLATES["files/_form"] = Ember.Handlebars.compile("<p><label for=\"title\">Title</label> {{input type=\"text\" id=\"title\" value=title}}</p>\r\n<p><label for=\"author\">Author</label> {{input type=\"text\" id=\"author\" value=author}}</p>\r\n<p><label for=\"contents\">Contents</label> {{textarea type=\"text\" id=\"contents\" value=contents}}</p>");

Ember.TEMPLATES["files/detail"] = Ember.Handlebars.compile("<h2>{{title}}</h2>\r\n<h3>by {{author}}</h3>\r\n<div>\r\n  {{markdown contents}}\r\n</div>  ");

Ember.TEMPLATES["files/edit"] = Ember.Handlebars.compile("<h3>{{company}}</h3>\r\n{{partial 'files/form'}}\r\n<button class=\"btn\" {{action 'editFile' this}}>Save</button>\r\n<h2>{{model.title}}</h2>\r\n<h3>by {{author}}</h3>\r\n<div>\r\n  {{markdown contents}}\r\n</div>  ");

Ember.TEMPLATES["files/new"] = Ember.Handlebars.compile("{{partial 'files/form'}}\r\n<button class=\"btn\" {{action 'addFile'}}>Save</button>");